# Generated by Django 4.1.5 on 2023-01-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0002_assetmanagement_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandlocation",
            options={"verbose_name_plural": "Brand Location"},
        ),
        migrations.AlterModelOptions(
            name="brandmanagement",
            options={"verbose_name_plural": "Brand Management"},
        ),
        migrations.AlterModelOptions(
            name="brandtypemanagement",
            options={"verbose_name_plural": "Brand Type Management"},
        ),
        migrations.AlterModelOptions(
            name="lightmanagement",
            options={"verbose_name_plural": "Light Management"},
        ),
        migrations.AlterModelOptions(
            name="materialmanagement",
            options={"verbose_name_plural": "Material Management"},
        ),
        migrations.AlterModelOptions(
            name="vendormanagement",
            options={"verbose_name_plural": "Vendor Management"},
        ),
        migrations.AlterModelTable(
            name="brandlocation",
            table="Brand Location",
        ),
        migrations.AlterModelTable(
            name="brandmanagement",
            table="Brand Management",
        ),
        migrations.AlterModelTable(
            name="brandtypemanagement",
            table="Brand Type Management",
        ),
        migrations.AlterModelTable(
            name="lightmanagement",
            table="Light Management",
        ),
        migrations.AlterModelTable(
            name="materialmanagement",
            table="Material Management",
        ),
        migrations.AlterModelTable(
            name="vendormanagement",
            table="Vendor Management",
        ),
    ]
