# Generated by Django 4.1.5 on 2023-02-23 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0006_alter_showroomdetail_e_mail"),
        ("Asset", "0004_alter_statusmanagement_visibilitylist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetmanagement",
            name="JobStatus",
        ),
        migrations.RemoveField(
            model_name="assetmanagement",
            name="Region",
        ),
        migrations.RemoveField(
            model_name="assetmanagement",
            name="ShowroomLocation",
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="AssetImage",
            field=models.URLField(
                default=datetime.datetime(
                    2023, 2, 23, 11, 2, 12, 77188, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="ClassManagement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.classmanagement",
            ),
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="Comments",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 2, 23, 11, 2, 19, 325962, tzinfo=datetime.timezone.utc
                ),
                max_length=240,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="CreateDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 23, 11, 2, 23, 581895, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="ExpiryDate",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 2, 23, 11, 2, 26, 429954, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="LightType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.lightmanagement",
            ),
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="Location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showroom.showroomdetail",
            ),
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="Status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.statusmanagement",
            ),
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="UpdatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 23, 11, 2, 33, 325999, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assetmanagement",
            name="Vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.vendormanagement",
            ),
        ),
        migrations.AlterField(
            model_name="assetmanagement",
            name="ADImage",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="assetmanagement",
            name="Brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.brandmanagement",
            ),
        ),
        migrations.AlterField(
            model_name="assetmanagement",
            name="BrandLocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.brandlocation",
            ),
        ),
        migrations.AlterField(
            model_name="assetmanagement",
            name="BrandingType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.brandtypemanagement",
            ),
        ),
        migrations.AlterField(
            model_name="assetmanagement",
            name="Material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.materialmanagement",
            ),
        ),
    ]
