# Generated by Django 4.1.5 on 2023-02-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0005_remove_assetmanagement_jobstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmanagement",
            name="Comments",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
