# Generated by Django 4.1.5 on 2023-02-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0006_alter_assetmanagement_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmanagement",
            name="CreateDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assetmanagement",
            name="UpdatedDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
