# Generated by Django 4.1.5 on 2023-02-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0007_alter_assetmanagement_createdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmanagement",
            name="ExpiryDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
