# Generated by Django 4.1.5 on 2023-02-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0008_alter_assetmanagement_expirydate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmanagement",
            name="Height",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="assetmanagement",
            name="ModelName",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="assetmanagement",
            name="Width",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
