# Generated by Django 4.1.5 on 2023-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0009_alter_assetmanagement_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmanagement",
            name="ADImage",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assetmanagement",
            name="AssetImage",
            field=models.URLField(blank=True, null=True),
        ),
    ]
