# Generated by Django 4.1.5 on 2023-02-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0010_alter_assetmanagement_adimage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetmanagement",
            options={"verbose_name_plural": "Asset Management"},
        ),
        migrations.AlterModelTable(
            name="assetmanagement",
            table="Asset Management",
        ),
    ]
