# Generated by Django 4.1.5 on 2023-01-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="imagemanagement",
            table="Degree Image Management",
        ),
    ]
