# Generated by Django 4.1.5 on 2023-01-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_alter_imagemanagement_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classmanagement",
            name="status",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="status",
        ),
        migrations.RemoveField(
            model_name="imagemanagement",
            name="status",
        ),
        migrations.RemoveField(
            model_name="lighttypelist",
            name="status",
        ),
        migrations.RemoveField(
            model_name="materialmanagement",
            name="status",
        ),
        migrations.DeleteModel(
            name="BrandLocation",
        ),
        migrations.DeleteModel(
            name="ClassManagement",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
        migrations.DeleteModel(
            name="ImageManagement",
        ),
        migrations.DeleteModel(
            name="LightTypeList",
        ),
        migrations.DeleteModel(
            name="MaterialManagement",
        ),
        migrations.DeleteModel(
            name="StatusManagement",
        ),
    ]
