# Generated by Django 4.1.5 on 2023-01-31 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0003_remove_classmanagement_status_remove_grade_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroomdetail",
            name="ASM",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showroom.asm",
            ),
        ),
        migrations.AlterField(
            model_name="showroomdetail",
            name="Manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showroom.manager",
            ),
        ),
        migrations.AlterField(
            model_name="showroomdetail",
            name="RSM",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showroom.rsm",
            ),
        ),
        migrations.AlterField(
            model_name="showroomdetail",
            name="Region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showroom.region",
            ),
        ),
        migrations.AlterField(
            model_name="showroomdetail",
            name="State",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showroom.state",
            ),
        ),
    ]
