# Generated by Django 4.1.5 on 2023-02-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_alter_showroomdetail_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroomdetail",
            name="Landline",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
