# Generated by Django 4.1.5 on 2023-02-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0003_alter_showroomdetail_landline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroomdetail",
            name="CUG_NO",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
