# Generated by Django 4.1.5 on 2023-02-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0005_alter_showroomdetail_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroomdetail",
            name="E_Mail",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
