# Generated by Django 4.1.3 on 2023-01-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name_plural": "Status",
                "db_table": "Status",
            },
        ),
        migrations.CreateModel(
            name="StatusManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "VisibilityList",
                    models.CharField(
                        choices=[("Assets", "Assets"), ("Vendor", "Vendor")],
                        max_length=120,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Status Management",
                "db_table": "Status Management",
            },
        ),
        migrations.CreateModel(
            name="MaterialManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Material Type List",
                "db_table": "Material Type List",
            },
        ),
        migrations.CreateModel(
            name="LightTypeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Light Type List",
                "db_table": "Light Type List",
            },
        ),
        migrations.CreateModel(
            name="ImageManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "360 Degree Image Management",
                "db_table": "Degree Image Management",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Grade",
                "db_table": "Grade",
            },
        ),
        migrations.CreateModel(
            name="FloorManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FloorDiagram", models.ImageField(upload_to="")),
                (
                    "ShowroomLocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="showroom.showroomdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Class Management",
                "db_table": "Class Management",
            },
        ),
        migrations.CreateModel(
            name="BrandManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Brand",
                "db_table": "Brand",
            },
        ),
        migrations.CreateModel(
            name="BrandLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Brand Type List",
                "db_table": "Brand Type List",
            },
        ),
    ]
