# Generated by Django 4.1.5 on 2023-01-31 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("showroom", "0003_remove_classmanagement_status_remove_grade_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name_plural": "Status",
                "db_table": "Status",
            },
        ),
        migrations.CreateModel(
            name="MaterialManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asset.statusmanagement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Material Type List",
                "db_table": "Material Type List",
            },
        ),
        migrations.CreateModel(
            name="LightTypeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asset.statusmanagement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Light Type List",
                "db_table": "Light Type List",
            },
        ),
        migrations.CreateModel(
            name="ImageManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asset.statusmanagement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "360 Degree Image Management",
                "db_table": "Degree Image Management",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asset.statusmanagement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Grade",
                "db_table": "Grade",
            },
        ),
        migrations.CreateModel(
            name="FloorManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FloorDiagram", models.ImageField(upload_to="")),
                (
                    "ShowroomLocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showroom.showroomdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asset.statusmanagement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Class Management",
                "db_table": "Class Management",
            },
        ),
        migrations.CreateModel(
            name="BrandLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asset.statusmanagement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Brand Type List",
                "db_table": "Brand Type List",
            },
        ),
    ]
