# Generated by Django 4.1.3 on 2023-01-31 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0001_initial"),
        ("Asset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ShowroomLocation", models.CharField(max_length=120)),
                ("BrandingType", models.CharField(max_length=120)),
                ("BrandLocation", models.CharField(max_length=120)),
                ("Brand", models.CharField(max_length=120)),
                ("ModelName", models.CharField(max_length=120)),
                ("Width", models.CharField(max_length=120)),
                ("Height", models.CharField(max_length=120)),
                ("Material", models.CharField(max_length=120)),
                ("Region", models.CharField(max_length=120)),
                ("ADImage", models.CharField(max_length=120)),
                ("JobStatus", models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameModel(
            old_name="LightTypeList",
            new_name="BrandTypeManagement",
        ),
        migrations.RenameModel(
            old_name="FloorManagement",
            new_name="FloorDiagramManagement",
        ),
        migrations.AlterModelOptions(
            name="brandtypemanagement",
            options={"verbose_name_plural": "BrandTypeManagement"},
        ),
        migrations.AlterModelTable(
            name="brandtypemanagement",
            table="BrandTypeManagement",
        ),
        migrations.CreateModel(
            name="VendorManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "VendorManagement",
                "db_table": "VendorManagement",
            },
        ),
        migrations.CreateModel(
            name="LightManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LightManagement",
                "db_table": "LightManagement",
            },
        ),
    ]
