# Generated by Django 4.1.5 on 2023-01-31 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0004_alter_showroomdetail_asm_and_more"),
        ("Asset", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandlocation",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.statusmanagement",
            ),
        ),
        migrations.AlterField(
            model_name="classmanagement",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.statusmanagement",
            ),
        ),
        migrations.AlterField(
            model_name="floormanagement",
            name="ShowroomLocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showroom.showroomdetail",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.statusmanagement",
            ),
        ),
        migrations.AlterField(
            model_name="imagemanagement",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.statusmanagement",
            ),
        ),
        migrations.AlterField(
            model_name="lighttypelist",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.statusmanagement",
            ),
        ),
        migrations.AlterField(
            model_name="materialmanagement",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Asset.statusmanagement",
            ),
        ),
    ]
