# Generated by Django 4.1.5 on 2023-01-31 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0002_alter_brandlocation_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Asset.statusmanagement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Brand",
                "db_table": "Brand",
            },
        ),
    ]
